const mongoose = require('mongoose');

const companySchema = new mongoose.Schema({
    companyName: { type: String, required: true,unique:true },
    maxUser: { type: Number, required: true },
    sssType: { type: Number, required: false },
    APIEndPoint: { type: String, required: false },
    labels: {
        doctorLabel: { type: String, required: false },
        vendorLabel: { type: String, required: false },
        stockistLabel: { type: String, required: false },
        areaLabel: { type: String, required: false },
        hqLabel: { type: String, required: false }
    },
    language: {
        type: [{
            name: { type: String, required: false },
            langCode: { type: String, required: false },
            status: { type: Boolean, required: false }
        }]
    },
    validation: {
        approvalUpto: { type: Number, required: false },
        editLockingPeriod: { type: Number, required: false },
        pob: { type: Boolean, required: false },
        payUrl: { type: Boolean, required: false },
        dcrDrugHalfDayCount: { type: Number, required: false },
        tpLockingPeriod: { type: Number, required: false },
        geoDistance: { type: Number, required: false },
        isDayPlan: { type: Boolean, required: false },
        geoLocMandatory: { type: Boolean, required: false },
        discountCalculatePob: { type: Boolean, required: false },
        isEdetailing: { type: Boolean, required: false },
        unlistedStatus: { type: Boolean, required: false },
        unlistedDocCall: { type: Boolean, required: false },
        unlistedVenCall: { type: Boolean, required: false },
        unlistedDocAvg: { type: Boolean, required: false },
        giftIssue: { type: Boolean, required: false },
        unlistedVenAvg: { type: Boolean, required: false },
        extraExcelColumns: { type: Boolean, required: false },
        prodTypeStatus: { type: Boolean, required: false },
        docCameraStatus: { type: Boolean, required: false },
        docChemSktSS: { type: Boolean, required: false },
        venCameraStatus: { type: Boolean, required: false },
        isERPExist: { type: Boolean, required: false },
        miscExpCameraStatus: { type: Boolean, required: false },
        sampleIssue: { type: Boolean, required: false },
        isMailModule: { type: Boolean, required: false },
        isMefEnabled: { type: Boolean, required: false },
        isTpLockMonthDay: { type: Boolean, required: false },
        venProductPOBCal: { type: String, required: false },
        stkProductPOBCal: { type: String, required: false },
        isDayPlanDCRMandatory: { type: Boolean, required: false },
        unlistedMgrDCR: { type: Boolean, required: false },
        unlistedVenCount: { type: Number, required: false, default: 50 },
        unlistedDocCount: { type: Number, required: false, default: 50 },
        mailReadDCRMandatory: { type: Boolean, required: false },
        isUserBlockCondition: { type: Boolean, required: false },
        IsSubmitAutoSunday: { type: Boolean, required: false },
        getAllStockistHqWise: { type: Boolean, required: false },
        productPOBCal: { type: String, required: false },
        dcrEndModification: { type: Boolean, required: false },
        targetEnableOnMobile: { type: Boolean, required: false },
        isPMTEnabled: { type: Boolean, required: false },
        dcrDrHalfDayCount: { type: Number, required: false },
        dcrDayEndEditEnabled: { type: Boolean, required: false },
        masterDocLimitCount: { type: Number, required: false },
        masterVendorLimitCount: { type: Number, required: false },
        isProdScheme: { type: Boolean, required: false },
        isDCRVisitShowLocAlert: { type: Boolean, required: false },
        isFocusProductLinkedWithEdetailing: { type: Boolean, required: false },
        prodGrpEnabled: { type: Boolean, required: false },
        isSSSwithERP: { type: Boolean, required: false },
        patchWiseReporting: { type: Boolean, required: false },
        dcrApproval: { type: Boolean, required: false },
        geoValidationOnBackDate: { type: Boolean, required: false },
        CRMModuleProposalWise: { type: Boolean, required: false },
        isChannelFormVisible: { type: Boolean, required: false },
        expenseApprovalByMgr: { type: Boolean, required: false },
        isTPDCRMandatory: { type: Boolean, required: false },
        isOnlineDCRStartDayEnd: { type: Boolean, required: false },
        autoCalculatePob: { type: Boolean, required: false },
        uploadPhotoMandatory: { type: Boolean, required: false },
        dcrWorkshop: { type: Boolean, required: false },
        customProductPrice: { type: Boolean, required: false },
        showCustomSpPrice: { type: Boolean, required: false },
        dayPlaneApproveMandatory: { type: Boolean, required: false },
        areaFreqVisitMandatory: { type: Boolean, required: false },
        geoDistanceCalculate: { type: Boolean, required: false },
        showCategoryOnDashboard: { type: Boolean, required: false },
        masterImagesUpload: { type: Boolean, required: false },
        providerFreqVisitMandatory: { type: Boolean, required: false },
    },
    degree: { type: [{ type: String, required: false }]},
    areaType: { type: [{ type: String, required: false }]},
    specialization: {type: [{ type: String, required: false }]},
    category: { type: [{ type: String, required: false }] },
    businessPotentials:{ type: [{ type: String, required: false }]},
    type:{ type: [{
        name: { type: String, required: false },
        langCode: { type: String, required: false },
        status: { type: Boolean, required: false }
    }] },
    expense: {
        daType: { type: String, required: false },
        expenseType: { type: String, required: false },
        stpApprovalUpto: { type: Number, required: false },
        expenseApprovalUpto: { type: Number, required: false }
    },
    isDivisionExist : { type: Boolean, required: false }, 
    isDefaultUserAndPass :{ type: Boolean, required: false }, 
    isAutoDayEnd :{ type: Boolean, required: false }, 
    autoSubmitDCRSunday :{ type: Boolean, required: false }, 
    isDCRProgressive : { type: Boolean, required: false }, 
    ismefExist: { type: Boolean, required: false },
    status: { type: Boolean, required: false,default:true },
    target : {
        targetInfo : { type: String, required: false }, 
        targetDuration : { type: String, required: false }, 
        targetType : { type: String, required: false }, 
        enableForMgr : {
            onlyForHqWise : { type: Boolean, required: false }, 
            desigLevel :{type:[{type:Number,required:false}]} , 
            rL :{type:[{type:Number,required:false}]} , 
        }
    }, 
    religion:{ type: [{ type: String, required: false }] }
},
{
    timestamps: false,
    versionKey: false
});

const Company = new mongoose.model('company', companySchema);
module.exports = Company;
